language: generic

services:
  - docker

before_install:
- docker image build -t create-react-app:dev .

script:
- docker container run -e CI=true create-react-app:dev npm run test

after_script:
- echo "SUCCESS!"
# - docker image build -t create-react-app:prod -f Dockerfile.prod .