language: generic

services:
  - docker

before_install:
- docker image build -t create-react-app:dev .

script:
- docker container run -e CI=true create-react-app:dev npm run test

after_script:
  -  docker image build -t create-react-app:prod -f Dockerfile.prod .

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-ap-south-1-259246440996"
  bucket_name: "test"
  on: 
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  