language: generic
sudo: required
services:
  - docker

before_install:
- docker pull regokan/create-react-app:dev

script:
- docker container run -e CI=true regokan/create-react-app:dev npm run test

after_script:
  -  docker pull regokan/create-react-app:prod

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-ap-south-1-259246440996"
  bucket_path: "test"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  