version: "3.8"
services:
  development:
    image: create-react-app:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - "./public:/app/public"
      - "./src:/app/src"
    environment:
      - CHOKIDAR_USEPOLLING=true
  production:
    image: create-react-app:prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"